import 'dart:typed_data';

import 'package:pslab/communication/commands_proto.dart';
import 'package:pslab/communication/packet_handler.dart';

class Uart2 {
  static const double _clockRate = 64e6;

  final PacketHandler packetHandler;
  final bool requiresWriteAcknowledgement;
  final CommandsProto _commands = CommandsProto();

  Uart2(this.packetHandler, {this.requiresWriteAcknowledgement = false});

  Future<void> configure(int baudRate) async {
    if (baudRate <= 0) {
      throw ArgumentError.value(baudRate, 'baudRate', 'Must be positive');
    }
    if (PacketHandler.boardType == BoardType.scpi) {
      throw UnsupportedError('UART2 is not available on this PSLab model');
    }

    final divider = ((_clockRate / baudRate) / 4 - 1).round();
    if (divider < 0 || divider > 0xffff) {
      throw ArgumentError.value(
        baudRate,
        'baudRate',
        'Cannot be generated by the UART2 clock',
      );
    }

    packetHandler.sendByte(_commands.uart2);
    packetHandler.sendByte(_commands.setBaud);
    packetHandler.sendInt(divider);
    final acknowledgement = await packetHandler.getAcknowledgement();
    if (acknowledgement != 1) {
      throw StateError(
        'UART2 rejected baud-rate configuration (ACK $acknowledgement)',
      );
    }
  }

  Future<bool> hasData() async {
    packetHandler.sendByte(_commands.uart2);
    packetHandler.sendByte(_commands.readUart2Status);
    return await _readResponseByte() != 0;
  }

  Future<int> readByte() async {
    packetHandler.sendByte(_commands.uart2);
    packetHandler.sendByte(_commands.readByte);
    return _readResponseByte();
  }

  Future<void> writeByte(int value) async {
    if (value < 0 || value > 0xff) {
      throw ArgumentError.value(value, 'value', 'Must fit in one byte');
    }
    packetHandler.sendByte(_commands.uart2);
    packetHandler.sendByte(_commands.sendByte);
    packetHandler.sendByte(value);
    if (requiresWriteAcknowledgement) {
      await packetHandler.getAcknowledgement();
    }
  }

  Future<void> write(List<int> values) async {
    for (final value in values) {
      await writeByte(value);
    }
  }

  Future<int> _readResponseByte() async {
    final response = Uint8List(1);
    final bytesRead = await packetHandler.read(response, 1);
    if (bytesRead != 1) {
      throw StateError('UART2 response timed out');
    }
    return response[0];
  }
}
