// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `setup_cp210x`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `EP_IN`, `EP_OUT`, `INTERFACE_ID`, `TX_QUEUE`, `USB_HANDLE`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `deref`, `deref`, `deref`, `deref`, `initialize`, `initialize`, `initialize`, `initialize`, `initialize`

Future<void> initDesktop({required int vid, required int pid}) =>
    RustLib.instance.api.crateApiSimpleInitDesktop(vid: vid, pid: pid);

Future<void> initAndroid({required int fd}) =>
    RustLib.instance.api.crateApiSimpleInitAndroid(fd: fd);

void setBaudRate({required int baudRate}) =>
    RustLib.instance.api.crateApiSimpleSetBaudRate(baudRate: baudRate);

void setDtr({required bool state}) =>
    RustLib.instance.api.crateApiSimpleSetDtr(state: state);

void setRts({required bool state}) =>
    RustLib.instance.api.crateApiSimpleSetRts(state: state);

void writeData({required List<int> data}) =>
    RustLib.instance.api.crateApiSimpleWriteData(data: data);

Future<Uint8List> readData(
        {required int bytesToRead, required int timeoutMs}) =>
    RustLib.instance.api
        .crateApiSimpleReadData(bytesToRead: bytesToRead, timeoutMs: timeoutMs);

void closeUsb() => RustLib.instance.api.crateApiSimpleCloseUsb();

bool checkDesktopDevicePresent() =>
    RustLib.instance.api.crateApiSimpleCheckDesktopDevicePresent();
